### ISSUE TITLE
Improve Powerline Folder Display 

### ISSUE THREAD

**Issue by amadeus** [cocopon/vaffle.vim#11]
Not sure if this is a Vaffle issue or a Powerline issue, however the reported folder has `//0//` before it, it would be nicer if this could be cleaner:

![example](http://wtf.amadeus.wtf/monosnap/Developmentdiscorddiscord_app_2017-11-01_10-35-07.png)

**Comment by cocopon** [comment]
That prefix is required to use Vaffle with multi-window. According to the Vim specification, buffers with the same name cannot exists at the same time.
