### ISSUE TITLE
Whether mappings avoid overriding default mappings or not

### ISSUE THREAD

**Issue by mopp** [cocopon/vaffle.vim#15]
Hi !

This is not an issue.
I would like to know what you think.

In this week, I sent PR #14 and it was merged ;)

After that, I had considered whether mappings avoid overriding default mappings or not again.
Because someone needs to set mapping himself when someone already uses mappings such as `h`, `l`.
I think it is a little bit annoying 😢 

Then, I considered alternative ways:
* Execute `:doautocmd FileType` after setting default mappings in vaffle.vim
* Define callback functions to override mappings

Thanks

**Comment by cocopon** [comment]
I think the former idea (Execute `:doautocmd FileType` after setting the default mappings) looks good to me.

**Comment by mopp** [comment]
ok, I follow your choice.

The default mappings of vaffle are defined when some mappings conflicts to them after the commit (https://github.com/cocopon/vaffle.vim/commit/bcdcb83e1fa475ad933e5937306f5b6e112bd857).

Then, this issue should be closed.

thank !
