### ISSUE TITLE
buffer wiped out

### ISSUE THREAD

**Issue by igungor** [cocopon/vaffle.vim#2]
hey, thanks for the plugin. it's just what i need really. complete clutter and dependency free, and just works. love the way batch renaming works just like `vidir`.

there's a minor thing that distracts me which is when you open vaffle, close it and open it again, "1 buffer wiped out" message is shown and it waits for the user to press a key.

is it about my configuration gets in the way?

**Comment by cocopon** [comment]
Thank you for reporting!
I've never seen the message in my environment... I think it's caused by cleaning outdated buffers, so I suppressed a message for wiping out these buffers. Does the problem solved? Please update to the latest version and try it.

**Comment by igungor** [comment]
It is solved. Thanks for the help!
