### ISSUE TITLE
open vaffle if no files are edited at vim startup

### ISSUE THREAD

**Issue by x4m3** [cocopon/vaffle.vim#20]
is there an option (or a command) to open vaffle when vim start if i start vim without any files?

for example, if i just run `vim`, vaffle would start to show me the files in the current directory.

i know that nerdtree does that, i was wondering if the same thing exists with vaffle.

thanks!

**Comment by yous** [comment]
Try this:
``` vim
autocmd VimEnter * nested
      \ if !argc() && line2byte(line('$') + 1) == -1 |
      \   Vaffle |
      \ endif
```
This opens Vaffle only when there's no files in the argument list and no content in the buffer.

**Comment by x4m3** [comment]
thank you! works like a charm!
