### ISSUE TITLE
Default mappings not working

### ISSUE THREAD

**Issue by markwu** [cocopon/vaffle.vim#21]
I saw you changed the default behavior of `default mappings`, it just ignored the keys that already mapped by other plugins or configs.

It takes me several minutes to find this issue. 

Can I have an option to force the default mappings to overwrite existing mappings?

**Comment by markwu** [comment]
Something like, 

``` vim
let g:vaffle_force_default_mapping_overwrite = 1
(You can leave the above variable 0 to follow your recent behavior change)
```

**Comment by mopp** [comment]
This issue may be related to the #15 .

**Comment by markwu** [comment]
Actually, I like your default mapping and it works very well. That's why I suggest give us an option to force the default  mapping overwrite the existence global mapping in vaffle buffer.

I don't need to worry about which default mapping doesn't work.

**Comment by cocopon** [comment]
Ah, I understand the problem. Thank you for your explanation.

**Comment by cocopon** [comment]
After following the advice #15, I fixed the behavior of overriding the default mappings. Is the problem solved?

**Comment by cocopon** [comment]
Feel free to reopen the issue if you still have a problem.
