### ISSUE TITLE
Default behavior of <Plug>(vaffle-open-selected-split) and <Plug>(vaffle-open-selected-vsplit).

### ISSUE THREAD

**Issue by mopp** [cocopon/vaffle.vim#24]
Sorry for taking your time many times...

I found the default behaviors differs from vim's `split/vsplit` after merging #17 .
You can confirm them following the steps below.
1. `vim -u NONE`
2. `:split` or `:vsplit`
3. `topleft split` or `rightbelow vsplit`

`splitright` and `splitbelow` is suitable for first my purpose.

There are two ways:
1. Keep them
2. Make `g:vaffle_open_selected_split_position` and `g:vaffle_open_selected_vsplit_position ` empty (`''`) (Vim's default behaviors)

Anyway, the document should be appended because `''` is also possible value.
https://github.com/cocopon/vaffle.vim/blob/master/doc/vaffle.txt#L240

I can make PR for this.
Working with yourself and close this issue is also OK 👍 

I did't notice them when I create PR. 
I'm really sorry 😢

**Comment by cocopon** [comment]
I think the latter (following the default behavior of Vim) is better. Could you create a PR for this?

**Comment by mopp** [comment]
thx !

I'm going to create PR
