### ISSUE TITLE
Stop notify about successful action 

### ISSUE THREAD

**Issue by TrySound** [cocopon/vaffle.vim#26]
Here's what I get after every action. It's quite noisy to press enter after making any change and approving (y/N) in some cases.

creating new file
![image](https://user-images.githubusercontent.com/5635476/44297781-02506f80-a2e0-11e8-84a7-d00e712d0da5.png)

renaming file
![image](https://user-images.githubusercontent.com/5635476/44297783-0f6d5e80-a2e0-11e8-8527-703f64f06bcd.png)

creating new directory
![image](https://user-images.githubusercontent.com/5635476/44297789-1b592080-a2e0-11e8-9834-d27a9c47a05a.png)

cancelling with escape
![image](https://user-images.githubusercontent.com/5635476/44297793-2d3ac380-a2e0-11e8-8e06-5d1c7dd5bfe8.png)

deleting file/dir
![image](https://user-images.githubusercontent.com/5635476/44297798-53f8fa00-a2e0-11e8-8236-26a56baaf69a.png)

**Comment by Shougo** [comment]
`set cmdheight=2` may fix the problem.

**Comment by TrySound** [comment]
@Shougo This worked as a temporary fix. Thanks.
