### ISSUE TITLE
Vaffle still delete previous buffer after 0bc35d2 for #31

### ISSUE THREAD

**Issue by markwu** [cocopon/vaffle.vim#38]
I think there are still bugs after this fix 0bc35d2  

The same scenario, you can produce the bug follow the steps:

1. Assume we have 3 files,~/a/1.txt, ~/a/2.txt/, ~/b/3.txt`.
2. `:Vaffle<cr>`, and open `~/a/1.txt`, use `:ls`, you will see `~/a/1.txt`
3. `:Vaffle<cr>`, and open `~/a/2.txt`, use `:ls`, you will see `~/a/1.txt`, `~/a/2.txt`
4. `:Vaffle ~/b<cr>`, and open `~/b/3.txt`, use `:ls`, you will see `~/a/1.txt`, `~/b/3.txt`. And `~/a/2.txt` disappeared in (removed from) the buffer list.

But, If I use `:edit ~/b` instead of `:Vaffle ~/b` to open the folder, Vaffle works well. I don't need to change anything.

I also try to fixed the code like following, seems solve the problem.

```vim
  if !isdirectory(path)
    " Open new directory buffer and overwrite it
    " (will be initialized by vaffle#event#on_bufenter)
    let dir = fnamemodify(path, ':h')
    execute printf('edit %s', fnameescape(dir))

    call vaffle#buffer#move_cursor_to_path(
          \ fnamemodify(path, ':p'))
    return
  else
    execute printf('edit %s', fnameescape(path))
  endif
```
Reference #31

**Comment by cocopon** [comment]
@markwu I'm trying to fix the problem in the branch. Could you try it?
https://github.com/cocopon/vaffle.vim/tree/fix-unexpected-overwriting

**Comment by markwu** [comment]
I just test the branch, it seems fix the problem. Thank you.

**Comment by cocopon** [comment]
Merged! Thank you for checking the fix.
