### ISSUE TITLE
Running :Vaffle opens the current file folder instead of Vim's working directory

### ISSUE THREAD

**Issue by zoomido** [cocopon/vaffle.vim#41]
Both `:Vaffle` and `:Vaffle %` opens a Vaffle buffer with the folder of the current file instead of Vim's current working dir.
I'm using [rooter](https://github.com/airblade/vim-rooter) to set the root dir in vim to the git root when opening a file but that shouldn't affect Vaffle.

To reproduce:
1a) Open any file in a subfolder in a git repo eg: `gitfolder/subfolder/file.txt`
1b) Rooter will correctly set the Vim's working dir to `gitfolder/`
2) Check current working directory for vim with `:pwd` (will show `gitfolder/`)
3) Run `:Vaffle`. Vaffle will open in `gitfolder/subfolder/` instead of `gitfolder/`

MacOS: 10.15.3
Neovim: v0.4.3 (Terminal Kitty / SSH)
vimrc: https://github.com/zoomido/.dotfiles/blob/master/init.vim

**Comment by cocopon** [comment]
Fixed! Please try the latest version. Thank you for reporting the issue.
