### ISSUE TITLE
Feature: Support floating windows

### ISSUE THREAD

**Issue by mintelm** [cocopon/vaffle.vim#42]
Hi,

is there a way to open the vaffle buffer in a floating window?

I'd expect to make a configuration for example like this:
let g:vaffle_layout = { 'window': { 'width': 0.9, 'height': 0.6, 'highlight': 'Debug' } }

**Comment by suliveevil** [comment]
https://github.com/liuchengxu/vim-which-key

This is a good example to use popup menu.

If Vaffle could also have this “step by step” and <kbd>Backspace</kbd> to go back feature, that would be even nicer!

**Comment by cocopon** [comment]
Interesting, but it seems to be difficult to run Vaffle inside Vim popup window because it cannot get keyboard focus. https://vimhelp.org/popup.txt.html#popup-intro

**Comment by suliveevil** [comment]
I’m just begin using vim-which-key.
If we can make those “open file/folder” as a function, 
then we define a function to a shortcut,
we will be able use which-key as vaffle’s UI😝

**Comment by cocopon** [comment]
I still cannot imagine vim-which-key integration, but if you are interested in this feature, please create a new issue (because it seems to be not directly related to this issue).

**Comment by suliveevil** [comment]
It’s out of the topic,I will stop here😂
