### ISSUE TITLE
Feature Request: Launch Vaffle from directory of current file

### ISSUE THREAD

**Issue by amadeus** [cocopon/vaffle.vim#6]
Hey, just wanted to say, been really liking this plugin!

To give a bit of a context for how I often work:

I `:cd` into a project directory, than often use a combination of CtrlP or Vaffle to open files as I work. Sometimes I open a file, but would then like to open another file within the same directory of the file that is open. Since I've been `:cd`d into a parent project directory, I have to re-navigate back in to open that file.

Perhaps a new command that launches Vaffle based on that file's directory? I still like the general functionality of adopting the current `pwd` as the starting place however, so not asking for a change in behavior, just a new command or possible argument for the current one!

P.S. I guess it would also be nice to have a way to open a file in a split instead of taking over the current buffer as well, but imo that's less necessary with the above feature request

**Comment by jack6000** [comment]
Vaffle already accepts an argument. See `:h vaffle-commands`
So `:Vaffle %:h` would open vaffle with the dir of the file beeing edited
Or maybe i didn't understand your problem...

**Comment by cocopon** [comment]
Thank you for using Vaffle! As @jack6000 said, `:Vaffle %:h` would satisfy your needs.

FYR, it's part of my .vimrc:
```vim
" Ctrl + U for opening a directory of the current file
" or the current working directory if it doesn't have a parent directory (e.g. empty buffer)
nnoremap <silent> <C-u> :execute 'Vaffle ' . ((strlen(bufname('')) == 0) ? '.' : '%:h')<CR>
```

**Comment by hoffi** [comment]
Hey, i also use `:Vaffle %:h`, however it would be nice if it could navigate the cursor to the current open file, like [NERDTreeFind](https://github.com/scrooloose/nerdtree/blob/master/doc/NERDTree.txt#L135) does.

**Comment by amadeus** [comment]
Yeah, I suppose I can just alias it. Fair enough.

How about the little P.S. note thought?

Being able to open a file in a split and not replace the Vaffle window?

**Comment by cocopon** [comment]
@hoffi Thank you for the request. It's about another feature so created the new issue #8.
