### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by narcisse82** [cocopon/vaffle.vim#61]
Hi Cocopon,

Maybe people that want to use this wonderful vaffle plugin would like having a little bit more information in the doc section. For instance, in my .vimrc, I have added these lines, which could be interesting:
augroup VimStartup
au!
au VimEnter * if expand("%") == "" && argc() == 0
\ | call vaffle#init('.')
\ | endif
au FileType vaffle setl bufhidden=wipe
augroup END

nnoremap - :Vaffle %:h

The 1st section allows launching vaffle when no file argument is given when starting vim / nvim.
The 2nd section (the "-" map command) allows to get a behavior similar to the one defined in the Tim Pope's vinegar plugin.
Do you think that it would be possible to add these lines in doc/vaffle.txt ?

Best regards
Stephane

**Comment by cocopon** [comment]
**1st section**:
- Is `expand("%") == "" &&` required?
- What does `au FileType vaffle setl bufhidden=wipe` do?

**2nd section**:
- It's too simple to add to the document.
