### ISSUE TITLE
[Feature Request] Show path/header at top

### ISSUE THREAD

**Issue by ten3roberts** [cocopon/vaffle.vim#62]
Currently it can be quite disorienting when navigating directories when you don't know where you are, especially when there are multiple directories of the same name, like 'src'

From what I've found when reading the docs and source code there is currently no way to display a line indicating the path to the current directory.

This can easily be implemented and toggleable by modifying the display and select functions to render and account for the header respectively.

## Example:
```
~/projects/test:
   a.c
   b.c
```
I am willing to implement the feature and open a pull request if needed.

**Comment by cocopon** [comment]
Thank you for your request, but at least for now, I'd rather not add any extra information to the buffer.

One of the concept of Vaffle is "simple". Each line expresses a single file object in the current design. It's quite simple.

If I accepted this feature, I would also need to consider similar features... list of available commands, file sizes, permissions, footer, etc. And it will become a rich but complex file manager... like Netrw.

If you want to put complemental information, I think that the status line is the place for it.

**Comment by ten3roberts** [comment]
I totally see what you're getting at. Putting it in the status line is probably a better idea, although unsure how that would conflict with plugins like lightline.

Is there currently any way to get the current directory of vaffle when except using getcwd and vaffle_autocd option?

Letting the user customize their statusline themselves by having vaffle populate a global or expose a function for the current dir is a much better idea.

**Comment by cocopon** [comment]
You can use `b:vaffle.dir` for that case. The implementation of vim-airline may help you:
https://github.com/vim-airline/vim-airline/blob/38c9f9ca3d1960d38d4d283cf62863ba9be8a6b7/autoload/airline/extensions.vim#L36

**Comment by cocopon** [comment]
Closed, feel free to reopen the issue if you still have a problem.
