### ISSUE TITLE
Arrow key bindings

### ISSUE THREAD

**Issue by cookiengineer** [cocopon/vaffle.vim#7]
I tried out vaffle and I really like it. Currently I'm trying to figure out how to map the arrow bindings to the same behaviours as hjkl; because when I casually browse the files I tend to use the arrow keys on my keyboard.

The behaviour of the Arrow keys currently is somehow unexplainable. Pressing the arrow-down key leads to a revert in buffer history and a "B" being typed (wat?).

Which methods do I need to modify to have support for arrow keys? I kind of found out that h and l are mapped via the "vaffle-open-parent" and "vaffle-open-current" settings; but I have no clue where the bindings for the navigational stuff is (I mean the up and down in buffer to select entries).

**Comment by cocopon** [comment]
Please tell me your environment (OS, Vim, .vimrc, terminal, etc.). Arrow keys work fine in my environment.

- macOS 10.12.6
- MacVim 8.0.891 (KaoriYa 20170807)
- .vimrc: https://github.com/cocopon/dotfiles/blob/master/.vimrc

**Comment by cocopon** [comment]
Reproduced the bug with Vim 8.0.844 in Terminal.app and now fixed it. Please see the following comment for the detail:
https://github.com/cocopon/vaffle.vim/commit/90dad16362d1045699195b703122a759a3d018d4#diff-c243ecf561f8b287f4671a6abdf724a0R25

**Comment by cookiengineer** [comment]
I was a bit too late. Can confirm, it now works perfectly. Thank you very much <3

For others experiencing the same: I used GNOME Terminal or UXTerm, with VIM 8.0.0987-1.
